config/routes.rb
# encoding: utf-8

#  Copyright (c) 2012-2025, Dachverband Schweizer Jugendparlamente. This file is part of
#  hitobito_dsj and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_dsj.

Rails.application.routes.draw do

  extend LanguageRouteScope

  language_scope do
    # Define wagon routes here

    resources :groups do
      resources :people do
        resources :notes, only: [:create, :destroy, :edit, :update]
      end

      resources :events, only: [] do # do not redefine events actions, only add new ones
        collection do
          get 'fundraising' => 'events#index', type: 'Event::Fundraising'
        end
      end
    end

    get 'list_fundraisings' => 'event/lists#fundraisings', as: :list_fundraisings
  end
end

app/controllers/dsj/notes_controller.rb
# frozen_string_literal: true

#  Copyright (c) 2012-2025, Dachverband Schweizer Jugendparlamente. This file is part of
#  hitobito_dsj and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_dsj.

module Dsj
  module NotesController
    extend ActiveSupport::Concern

    included do
      helper_method :subject_path, :update_path

      prepend_before_action :group, only: [:edit]
    end

    def update
      authorize!(:update, note)
      @note.assign_attributes(permitted_params.merge(author_id: current_user.id))
      @note.save

      respond_to do |format|
        format.html { redirect_to subject_path }
      end
    end

    def edit
      authorize!(:update, note)

      respond_to do |format|
        format.html
      end
    end

    private

    def update_path
      if @note.subject_type == Group.name
        group_note_path(group_id: group.id, id: @note.id)
      else
        group_person_note_path(group_id: group.id, person_id: subject.id, id: @note.id)
      end
    end
  end
end

app/helpers/sheet/note.rb
#  Copyright (c) 2019, Dachverband Schweizer Jugendparlamente. This file is part of
#  hitobito and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito.

module Sheet
  class Note < Base
    self.parent_sheet = Sheet::Person

    def title
      I18n.t("notes.actions_edit.title")
    end

    def current_parent_nav_path
      view.group_people_path(parent_sheet.parent_sheet.entry.id,
        parent_sheet.entry.id)
    end
  end
end

app/views/notes/_note.html.haml
-#  Copyright (c) 2012-2019, Dachverband Schweizer Jugendparlamente. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

.row-fluid.note{id: dom_id(note), class: ('is-current-subject' unless show_subject)}
  - if show_subject
    .note-image
      - case note.subject
      - when Group
        = image_tag('group.svg')
      - when Person
        %img{src: note.subject.picture}

  .note-body
    - if show_subject
      = assoc_link(note.subject)

    %small.muted.note-author
      = person_link(note.author)
      .note-date
        = t('.created', time_ago: time_ago_in_words(note.created_at))
      - if can?(:update, note)
        - if note.subject.is_a? Person
          = link_to icon(:edit), edit_group_person_note_path(@group, note.subject, note)
      - if can?(:destroy, note)
        = link_to icon(:'trash-alt', filled: false),
                  note_path(note, @group.id),
                  method: :delete,
                  remote: true,
                  data: { confirm: ti(:confirm_delete) }

    = auto_link(simple_format(note.text))

app/views/notes/edit.html.haml
-#  Copyright (c) 2019, Dachverband Schweizer Jugendparlamente. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

#main.row-fluid
  = crud_form(@note, :text, cancel_url: subject_path, url: update_path)